//! Population management: subpopulations split by feasibility, diversity management,
//! adaptive penalties and best-solution tracking.
//!
//! The C++ version stores `Individual*` and tracks proximities through a multiset of
//! `(distance, Individual*)`. Here every population member gets a unique id at insertion,
//! and proximity lists are sorted vectors of `(distance, id)`. The behavior is identical
//! and deterministic (the C++ ties on pointer addresses, ids play the same role).

use std::collections::VecDeque;
use std::time::Duration;

use crate::algorithm_parameters::AlgorithmParameters;
use crate::individual::Individual;
use crate::local_search::LocalSearch;
use crate::params::Params;
use crate::split::Split;
use crate::util::{format_double, MY_EPSILON};

/// One member of a subpopulation.
struct PopIndiv {
    id: u64,
    indiv: Individual,
    /// Biased fitness of the solution.
    biased_fitness: f64,
    /// Other individuals of the same subpopulation, ordered by increasing proximity.
    proximity: Vec<(f64, u64)>,
}

type SubPopulation = Vec<PopIndiv>;

/// Identifies an individual selected from one of the two subpopulations.
#[derive(Clone, Copy)]
pub struct Selection {
    feasible: bool,
    index: usize,
}

pub struct Population {
    /// Feasible subpopulation, kept ordered by increasing penalized cost.
    feasible_subpop: SubPopulation,
    /// Infeasible subpopulation, kept ordered by increasing penalized cost.
    infeasible_subpop: SubPopulation,
    /// Load feasibility of the recent individuals generated by the LS.
    list_feasibility_load: VecDeque<bool>,
    /// Duration feasibility of the recent individuals generated by the LS.
    list_feasibility_duration: VecDeque<bool>,
    /// Time stamps and values of successive best solutions.
    search_progress: Vec<(Duration, f64)>,
    /// Best solution found during the current restart of the algorithm.
    best_solution_restart: Individual,
    /// Best solution found during the complete execution of the algorithm.
    best_solution_overall: Individual,
    /// Next unique id handed to an inserted individual.
    next_id: u64,
}

impl Population {
    pub fn new(params: &mut Params) -> Self {
        Self {
            feasible_subpop: Vec::new(),
            infeasible_subpop: Vec::new(),
            list_feasibility_load: VecDeque::from(vec![true; params.ap.nb_iter_penalty_management]),
            list_feasibility_duration: VecDeque::from(vec![
                true;
                params.ap.nb_iter_penalty_management
            ]),
            search_progress: Vec::new(),
            best_solution_restart: Individual::new(params),
            best_solution_overall: Individual::new(params),
            next_id: 0,
        }
    }

    /// Creates an initial population of individuals.
    pub fn generate_population(
        &mut self,
        params: &mut Params,
        split: &mut Split,
        local_search: &mut LocalSearch,
    ) {
        if params.verbose {
            println!("----- BUILDING INITIAL POPULATION");
        }
        let mut i = 0;
        while i < 4 * params.ap.mu
            && (i == 0
                || params.ap.time_limit == 0.0
                || params.start_time.elapsed().as_secs_f64() < params.ap.time_limit)
        {
            let mut random_indiv = Individual::new(params);
            split.general_split(params, &mut random_indiv, params.nb_vehicles);
            let (penalty_capacity, penalty_duration) =
                (params.penalty_capacity, params.penalty_duration);
            local_search.run(
                params,
                &mut random_indiv,
                penalty_capacity,
                penalty_duration,
            );
            self.add_individual(&random_indiv, true, params);
            if !random_indiv.eval.is_feasible && params.rng.next() % 2 == 0 {
                // Repair half of the solutions in case of infeasibility
                local_search.run(
                    params,
                    &mut random_indiv,
                    penalty_capacity * 10.0,
                    penalty_duration * 10.0,
                );
                if random_indiv.eval.is_feasible {
                    self.add_individual(&random_indiv, false, params);
                }
            }
            i += 1;
        }
    }

    /// Adds an individual to the population (survivor selection is automatically
    /// triggered whenever the population reaches its maximum size).
    /// Returns true if a new best solution of the run has been found.
    pub fn add_individual(
        &mut self,
        indiv: &Individual,
        update_feasible: bool,
        params: &Params,
    ) -> bool {
        if update_feasible {
            self.list_feasibility_load
                .push_back(indiv.eval.capacity_excess < MY_EPSILON);
            self.list_feasibility_duration
                .push_back(indiv.eval.duration_excess < MY_EPSILON);
            self.list_feasibility_load.pop_front();
            self.list_feasibility_duration.pop_front();
        }

        // Find the adequate subpopulation in relation to the individual feasibility
        let id = self.next_id;
        self.next_id += 1;
        let subpop = if indiv.eval.is_feasible {
            &mut self.feasible_subpop
        } else {
            &mut self.infeasible_subpop
        };

        // Insert a copy of the individual and update the proximity structures
        // by calculating the inter-individual distances
        let mut proximity = Vec::with_capacity(subpop.len() + 1);
        for other in subpop.iter_mut() {
            let distance = broken_pairs_distance(indiv, &other.indiv, params.nb_clients);
            insert_proximity(&mut other.proximity, distance, id);
            insert_proximity(&mut proximity, distance, other.id);
        }

        // Identify the correct location in the subpopulation and insert the individual
        let mut place = subpop.len();
        while place > 0
            && subpop[place - 1].indiv.eval.penalized_cost > indiv.eval.penalized_cost - MY_EPSILON
        {
            place -= 1;
        }
        subpop.insert(
            place,
            PopIndiv {
                id,
                indiv: indiv.clone(),
                biased_fitness: 0.0,
                proximity,
            },
        );

        // Trigger a survivor selection if the maximum subpopulation size is exceeded
        if subpop.len() > params.ap.mu + params.ap.lambda {
            while subpop.len() > params.ap.mu {
                Self::remove_worst_biased_fitness(subpop, &params.ap);
            }
        }

        // Track best solution
        if indiv.eval.is_feasible
            && indiv.eval.penalized_cost
                < self.best_solution_restart.eval.penalized_cost - MY_EPSILON
        {
            self.best_solution_restart.clone_from(indiv); // clone_from reuses the existing buffers
            if indiv.eval.penalized_cost
                < self.best_solution_overall.eval.penalized_cost - MY_EPSILON
            {
                self.best_solution_overall.clone_from(indiv);
                self.search_progress
                    .push((params.start_time.elapsed(), indiv.eval.penalized_cost));
            }
            true
        } else {
            false
        }
    }

    /// Evaluates the biased fitness of all individuals in the subpopulation.
    fn update_biased_fitnesses(pop: &mut SubPopulation, ap: &AlgorithmParameters) {
        // Ranking the individuals based on their diversity contribution
        // (decreasing order of broken-pairs distance)
        let mut ranking: Vec<(f64, usize)> = (0..pop.len())
            .map(|i| {
                (
                    -average_broken_pairs_distance_closest(&pop[i], ap.nb_close),
                    i,
                )
            })
            .collect();
        ranking.sort_by(|a, b| a.0.total_cmp(&b.0).then(a.1.cmp(&b.1)));

        // Updating the biased fitness values
        if pop.len() == 1 {
            pop[0].biased_fitness = 0.0;
        } else {
            let size = pop.len();
            for (rank, &(_, indiv_index)) in ranking.iter().enumerate() {
                // Ranking from 0 to 1
                let div_rank = rank as f64 / (size - 1) as f64;
                let fit_rank = indiv_index as f64 / (size - 1) as f64;
                if size <= ap.nb_elite {
                    // Elite individuals cannot be smaller than population size
                    pop[indiv_index].biased_fitness = fit_rank;
                } else {
                    pop[indiv_index].biased_fitness =
                        fit_rank + (1.0 - ap.nb_elite as f64 / size as f64) * div_rank;
                }
            }
        }
    }

    /// Removes the worst individual in terms of biased fitness.
    fn remove_worst_biased_fitness(pop: &mut SubPopulation, ap: &AlgorithmParameters) {
        Self::update_biased_fitnesses(pop, ap);
        if pop.len() <= 1 {
            panic!("Eliminating the best individual: this should not occur in HGS");
        }

        let mut worst_position = 0;
        let mut is_worst_clone = false;
        let mut worst_biased_fitness = -1.0e30;
        for (i, item) in pop.iter().enumerate().skip(1) {
            // A distance equal to 0 indicates that a clone exists
            let is_clone = average_broken_pairs_distance_closest(item, 1) < MY_EPSILON;
            if (is_clone && !is_worst_clone)
                || (is_clone == is_worst_clone && item.biased_fitness > worst_biased_fitness)
            {
                worst_biased_fitness = item.biased_fitness;
                is_worst_clone = is_clone;
                worst_position = i;
            }
        }

        // Remove the individual from the population and clean its distances
        // from the proximity structures of the other individuals
        let worst = pop.remove(worst_position);
        for other in pop.iter_mut() {
            let position = other
                .proximity
                .iter()
                .position(|&(_, id)| id == worst.id)
                .expect("each member references every other member of its subpopulation");
            other.proximity.remove(position);
        }
    }

    /// Cleans all solutions and generates a new initial population
    /// (only used when running HGS until a time limit).
    pub fn restart(
        &mut self,
        params: &mut Params,
        split: &mut Split,
        local_search: &mut LocalSearch,
    ) {
        if params.verbose {
            println!("----- RESET: CREATING A NEW POPULATION -----");
        }
        self.feasible_subpop.clear();
        self.infeasible_subpop.clear();
        self.best_solution_restart = Individual::new(params);
        self.generate_population(params, split, local_search);
    }

    /// Adaptation of the penalty parameters.
    pub fn manage_penalties(&mut self, params: &mut Params) {
        // Setting some bounds [0.1, 100000] to the penalty values for safety
        let fraction_feasible_load = fraction_true(&self.list_feasibility_load);
        if fraction_feasible_load < params.ap.target_feasible - 0.05
            && params.penalty_capacity < 100000.0
        {
            params.penalty_capacity =
                (params.penalty_capacity * params.ap.penalty_increase).min(100000.0);
        } else if fraction_feasible_load > params.ap.target_feasible + 0.05
            && params.penalty_capacity > 0.1
        {
            params.penalty_capacity =
                (params.penalty_capacity * params.ap.penalty_decrease).max(0.1);
        }

        let fraction_feasible_duration = fraction_true(&self.list_feasibility_duration);
        if fraction_feasible_duration < params.ap.target_feasible - 0.05
            && params.penalty_duration < 100000.0
        {
            params.penalty_duration =
                (params.penalty_duration * params.ap.penalty_increase).min(100000.0);
        } else if fraction_feasible_duration > params.ap.target_feasible + 0.05
            && params.penalty_duration > 0.1
        {
            params.penalty_duration =
                (params.penalty_duration * params.ap.penalty_decrease).max(0.1);
        }

        // Update the evaluations
        for item in self.infeasible_subpop.iter_mut() {
            item.indiv.eval.penalized_cost = item.indiv.eval.distance
                + params.penalty_capacity * item.indiv.eval.capacity_excess
                + params.penalty_duration * item.indiv.eval.duration_excess;
        }

        // If needed, reorder the individuals in the infeasible subpopulation since the
        // penalty values have changed (simple bubble sort for the sake of simplicity)
        let size = self.infeasible_subpop.len();
        for i in 0..size {
            for j in 0..size - i - 1 {
                if self.infeasible_subpop[j].indiv.eval.penalized_cost
                    > self.infeasible_subpop[j + 1].indiv.eval.penalized_cost + MY_EPSILON
                {
                    self.infeasible_subpop.swap(j, j + 1);
                }
            }
        }
    }

    /// Selects an individual by binary tournament in the union of the feasible and
    /// infeasible subpopulations. The returned handle stays valid until the next
    /// mutation of the population.
    pub fn get_binary_tournament(&mut self, params: &mut Params) -> Selection {
        let total_size = self.feasible_subpop.len() + self.infeasible_subpop.len();
        assert!(total_size > 0, "binary tournament on an empty population");

        // Picking two individuals with uniform distribution over the union of subpopulations
        let place1 = params.rng.uniform_below(total_size as u32) as usize;
        let place2 = params.rng.uniform_below(total_size as u32) as usize;

        Self::update_biased_fitnesses(&mut self.feasible_subpop, &params.ap);
        Self::update_biased_fitnesses(&mut self.infeasible_subpop, &params.ap);

        let selection1 = self.resolve_place(place1);
        let selection2 = self.resolve_place(place2);

        // Keeping the best of the two in terms of biased fitness
        if self.member(selection1).biased_fitness < self.member(selection2).biased_fitness {
            selection1
        } else {
            selection2
        }
    }

    fn resolve_place(&self, place: usize) -> Selection {
        if place >= self.feasible_subpop.len() {
            Selection {
                feasible: false,
                index: place - self.feasible_subpop.len(),
            }
        } else {
            Selection {
                feasible: true,
                index: place,
            }
        }
    }

    fn member(&self, selection: Selection) -> &PopIndiv {
        if selection.feasible {
            &self.feasible_subpop[selection.index]
        } else {
            &self.infeasible_subpop[selection.index]
        }
    }

    /// Accesses an individual through a tournament selection handle.
    pub fn individual(&self, selection: Selection) -> &Individual {
        &self.member(selection).indiv
    }

    /// Accesses the best feasible individual.
    pub fn best_feasible(&self) -> Option<&Individual> {
        self.feasible_subpop.first().map(|item| &item.indiv)
    }

    /// Accesses the best infeasible individual.
    pub fn best_infeasible(&self) -> Option<&Individual> {
        self.infeasible_subpop.first().map(|item| &item.indiv)
    }

    /// Accesses the best found solution at all time.
    pub fn best_found(&self) -> Option<&Individual> {
        if self.best_solution_overall.eval.penalized_cost < 1.0e29 {
            Some(&self.best_solution_overall)
        } else {
            None
        }
    }

    /// Prints population state.
    pub fn print_state(&self, nb_iter: usize, nb_iter_no_improvement: usize, params: &Params) {
        if !params.verbose {
            return;
        }
        print!(
            "It {:6} {:6} | T(s) {:.2}",
            nb_iter,
            nb_iter_no_improvement,
            params.start_time.elapsed().as_secs_f64()
        );

        if let Some(best) = self.best_feasible() {
            print!(
                " | Feas {} {:.2} {:.2}",
                self.feasible_subpop.len(),
                best.eval.penalized_cost,
                get_average_cost(&self.feasible_subpop, params.ap.mu)
            );
        } else {
            print!(" | NO-FEASIBLE");
        }

        if let Some(best) = self.best_infeasible() {
            print!(
                " | Inf {} {:.2} {:.2}",
                self.infeasible_subpop.len(),
                best.eval.penalized_cost,
                get_average_cost(&self.infeasible_subpop, params.ap.mu)
            );
        } else {
            print!(" | NO-INFEASIBLE");
        }

        print!(
            " | Div {:.2} {:.2}",
            get_diversity(&self.feasible_subpop, params.ap.mu),
            get_diversity(&self.infeasible_subpop, params.ap.mu)
        );
        print!(
            " | Feas {:.2} {:.2}",
            fraction_true(&self.list_feasibility_load),
            fraction_true(&self.list_feasibility_duration)
        );
        print!(
            " | Pen {:.2} {:.2}",
            params.penalty_capacity, params.penalty_duration
        );
        println!();
    }

    /// Exports in a file the history of solution improvements.
    pub fn export_search_progress(
        &self,
        file_name: &str,
        instance_name: &str,
        seed: u64,
    ) -> std::io::Result<()> {
        let mut output = String::new();
        for (time, value) in &self.search_progress {
            output.push_str(&format!(
                "{};{};{};{}\n",
                instance_name,
                seed,
                format_double(*value),
                format_double(time.as_secs_f64())
            ));
        }
        std::fs::write(file_name, output)
    }
}

/// Distance measure between two individuals, used for diversity calculations.
fn broken_pairs_distance(indiv1: &Individual, indiv2: &Individual, nb_clients: usize) -> f64 {
    let mut differences = 0;
    for j in 1..=nb_clients {
        if indiv1.successors[j] != indiv2.successors[j]
            && indiv1.successors[j] != indiv2.predecessors[j]
        {
            differences += 1;
        }
        if indiv1.predecessors[j] == 0 && indiv2.predecessors[j] != 0 && indiv2.successors[j] != 0 {
            differences += 1;
        }
    }
    differences as f64 / nb_clients as f64
}

/// Inserts (distance, id) in a proximity list kept sorted by (distance, id).
fn insert_proximity(proximity: &mut Vec<(f64, u64)>, distance: f64, id: u64) {
    let position = proximity
        .partition_point(|&(d, other_id)| d < distance || (d == distance && other_id < id));
    proximity.insert(position, (distance, id));
}

/// Returns the average broken pairs distance of this individual with the
/// `nb_closest` individuals of its subpopulation.
fn average_broken_pairs_distance_closest(item: &PopIndiv, nb_closest: usize) -> f64 {
    let max_size = nb_closest.min(item.proximity.len());
    let mut result = 0.0;
    for entry in &item.proximity[..max_size] {
        result += entry.0;
    }
    result / max_size as f64
}

/// Returns the average diversity value among the `mu` best individuals of the subpopulation.
fn get_diversity(pop: &SubPopulation, mu: usize) -> f64 {
    // Only monitoring the "mu" better solutions to avoid too much noise in the measurements
    let size = mu.min(pop.len());
    if size == 0 {
        return -1.0;
    }
    let mut average = 0.0;
    for item in &pop[..size] {
        average += average_broken_pairs_distance_closest(item, size);
    }
    average / size as f64
}

/// Returns the average solution value among the `mu` best individuals of the subpopulation.
fn get_average_cost(pop: &SubPopulation, mu: usize) -> f64 {
    // Only monitoring the "mu" better solutions to avoid too much noise in the measurements
    let size = mu.min(pop.len());
    if size == 0 {
        return -1.0;
    }
    let mut average = 0.0;
    for item in &pop[..size] {
        average += item.indiv.eval.penalized_cost;
    }
    average / size as f64
}

fn fraction_true(list: &VecDeque<bool>) -> f64 {
    list.iter().filter(|&&value| value).count() as f64 / list.len() as f64
}
